### ISSUE TITLE
Launch new jobs page

### ISSUE THREAD

**Issue by gcstaublin** [Upstatement/blades#37]
For launch, we need to satisfy these check boxes.

### Critical
- [x] Decide if the weirdness seen in local versions of the HP is real or not @thetmkay 
- [x] Gravity forms not displaying on individual apprenticeship pages. @jarednova   
This can be removed for launch, and we can send people to the standalone form, if needed.
http://ups.staging.wpengine.com/careers/development-apprentice/
- [x] Main nav. Should it say `Jobs` or `Careers` @jarednova 
- [x] Redirect Jobs to Careers @jarednova 
- [x] Current Development Apprentice posting as an Aug. 22 deadline. Update that? @jarednova 
- [x] Tweak copy block at top of Careers landing page. @gcstaublin
- [x] Tweak Culture and Benefits copy block @gcstaublin

### Enhancements
If these are not tackled prior to launch, they will be refined shortly thereafter
- [x] Tweak size of job titles on landing page. @gcstaublin
- [x] Refine the `Tell me more` button on a job link on landing page @gcstaublin
- [x] Refine `Show me more` button on the teasers on landing page @gcstaublin
- [ ] Devise a method of returning users to job posting once they reach bottom of landing page. @gcstaublin

**Comment by mswartz** [comment]
Gonna call this closed.
