### ISSUE TITLE
"Counting" JS for permutations section in RH Bookmark case study

### ISSUE THREAD

**Issue by ebaker1736** [Upstatement/blades#58]
We'd like to have the final "result" number in this section to animate up to its final total, à la Regis's counting stats in the Hechinger case study.

![screen shot 2015-09-10 at 2 49 08 pm](https://cloud.githubusercontent.com/assets/8629395/9797816/2127acc4-57cb-11e5-8816-3a6d00e28c69.png)

That number exists as live text within an svg, `rh-bookmark--result.svg`. The markup for the entire section can be found in `rh-bookmark--math-module.twig`. 

Regis's counting script can be found on lines 43 through 63 of `thr.js`.

**Comment by emmagard** [comment]
Resolved in above referenced commit.
